name: sourceforge..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: http://tdrive.manofuranium.workers.dev/romdaw.zip
  ROM_NAME: OneUI
  ZIP_NAME: OneUI
  SFDIRA: cd /home/pfs/project/rui-ports/YSL
  SFDIRAB: cd /home/pfs/project/rui-ports/test2
  DATE_TODAY: 20200712
  ANDROID_VERSION: 09
  PASSWORD: ${{ secrets.PASSWORD }}
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo apt update 2>/dev/null | grep packages
            sudo apt install wget
            sudo apt-get install p7zip-full
            sudo -E apt-get install expect

       - name: Downloading the File
         run: |
            mkdir file
            sudo chmod 0777 file
            cd file
            sudo aria2c $ROM_URL
            mv *.zip VOS3.0_KamateraEdition_YSL.zip
            
       - name: Uploading 
         run: |
            cd file  
            expect -c "
            spawn sftp ruiii@frs.sourceforge.net
            expect \"yes/no\"
            send \"yes\r\"
            expect \"Password\"
            send \"${{ secrets.PASSWORD }}\r\"
            expect \"sftp> \"
            send \"$SFDIRA\r\"
            set timeout -1
            send \"put VOS*.zip\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            interact"
            expect -c "
            spawn sftp ruiii@frs.sourceforge.net
            expect \"Password\"
            send \"${{ secrets.PASSWORD }}\r\"
            expect \"sftp> \"
            send \"$SFDIRAB\r\"
            set timeout -1
            send \"put file.zip\r\"
            expect \"Uploading\"
            expect \"100%\"
            expect \"sftp>\"
            send \"bye\r\"
            interact"
            
